gateway:
  ip: 192.168.1.116

token:
  expiration_time: 864
  secret: kakfjkladsjfladksjflljsecret

login:
  url:
    path: /users/login


spring:
  data-source:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: root
    password: abcds

  jpa:
    hibernate:
      ddl-auto: update
