gateway:
  ip: 192.168.1.116

token:
  expiration_time: 864
  secret: kakfjkladsjfladksjfllj

login:
  url:
    path: /users/login

albums:
  url: http://ALBUMS-WS/users/%s/albums


spring:
  data-source:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: root
    password: abcd

  jpa:
    hibernate:
      ddl-auto: update
